lints.workspace = true

[package]
edition.workspace = true
license.workspace = true
name = "generator_test"
rust-version.workspace = true
version.workspace = true

[dependencies]
futures = "0.3"

[dev-dependencies]
rt-local = "0.1"
