lints.workspace = true

[package]
edition.workspace = true
license.workspace = true
name = "salsa_test"
rust-version.workspace = true
version.workspace = true

[dependencies]
color-eyre.workspace = true
crossbeam-channel = "0.5.15"
dashmap = { version = "6", features = ["raw-api"] }
notify-debouncer-mini = "0.4.1"
ordered-float = "5.0.0"
salsa = "0.23"
