# Debtmap Configuration

[entropy]
enabled = true
weight = 0.5
min_tokens = 10
pattern_threshold = 0.7

[thresholds]
complexity = 10
duplication = 50
max_file_length = 500
max_function_length = 50

[languages]
enabled = ["rust"]

[ignore]
patterns = [
    "target/**",
    "venv/**",
    "node_modules/**",
    "*.min.js"
]

[output]
default_format = "markdown"
