enable_alias_analysis = true
enable_jump_tables = true
enable_llvm_abi_extensions = true
enable_probestack = true
machine_code_cfg_info = true
opt_level = "speed"
preserve_frame_pointers = true
probestack_strategy = "inline"
regalloc_checker = true
stack_switch_model = "update_windows_tib"
unwind_info = true
use_colocated_libcalls = false
