lints.workspace = true

[package]
edition.workspace = true
license.workspace = true
name = "cranefrick_mlir"
rust-version.workspace = true
version.workspace = true

[dependencies]
cranefrick_hlir = { path = "../hlir" }
serde = { workspace = true, default-features = false, features = [
    "alloc",
    "derive",
] }
cranefrick_utils = { workspace = true, features = [
    "insert_or_push",
    "shortname",
] }
tracing.workspace = true
