lints.workspace = true

[package]
edition.workspace = true
license.workspace = true
name = "cranium_veri_engine"
rust-version.workspace = true
version.workspace = true

[dependencies]
cranium_isle.workspace = true
