lints.workspace = true

[package]
edition.workspace = true
license.workspace = true
name = "egg_test"
rust-version.workspace = true
version.workspace = true

[dependencies]
color-eyre.workspace = true
egg = "0.10"
ordered-float = "5.0.0"
rayon = "1"
