lints.workspace = true

[package]
edition.workspace = true
license.workspace = true
name = "frick_async_runtime"
rust-version.workspace = true
version.workspace = true

[dependencies]
tracing.workspace = true
