lints.workspace = true

[package]
edition.workspace = true
license.workspace = true
name = "logos_test"
rust-version.workspace = true
version.workspace = true

[dependencies]
logos = { workspace = true }
