lints.workspace = true

[package]
edition.workspace = true
license.workspace = true
name = "cranelift_test"
rust-version.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
cranelift.workspace = true
target-lexicon = "0.13"
