lints.workspace = true

[package]
edition.workspace = true
license.workspace = true
name = "chess_test"
rust-version.workspace = true
version.workspace = true

[dependencies]
color-eyre.workspace = true
shakmaty = "0.29"
