lints.workspace = true

[package]
edition.workspace = true
license.workspace = true
name = "koopa_test"
rust-version.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
clap = { version = "4", features = ["derive"] }
koopa = "0.0.8"
