lints.workspace = true

[package]
edition.workspace = true
license.workspace = true
name = "indicatif_test"
rust-version.workspace = true
version.workspace = true

[dependencies]
tracing.workspace = true
tracing-indicatif = "0.3"
tracing-subscriber = { workspace = true, features = ["env-filter"] }
