lints.workspace = true

[package]
edition.workspace = true
license.workspace = true
name = "llvmenv"
rust-version.workspace = true
version.workspace = true

[dependencies]
bytes = "1.1"
clap = { workspace = true, features = ["derive"] }
color-eyre = { version = "0.6", features = ["capture-spantrace"] }
dirs = "6"
fs_extra = "1.2"
futures = "0.3.8"
glob = "0.3"
indicatif = "0.18"
itertools = "0.14"
lazy_static = "1.4"
num_cpus = "1.13.0"
regex = "1"
reqwest = { version = "0.12", features = ["blocking", "stream"] }
semver = "1"
serde = { workspace = true, features = ["derive"] }
shellexpand = "3"
tar = "0.4"
tempfile = "3.1.0"
tokio = { version = "1", features = ["rt-multi-thread"] }
toml = "0.9"
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }
url = "2.2.0"
which = { version = "4", default-features = false }
xz2 = "0.1.6"

[dev-dependencies]
tracing-subscriber.workspace = true
