lints.workspace = true

[package]
edition.workspace = true
license.workspace = true
name = "futures_test"
rust-version.workspace = true
version.workspace = true

[dependencies]
color-eyre.workspace = true
tracing.workspace = true
tracing-subscriber = { workspace = true }
